name: API CI - RealEstate                                                 # Nombre del flujo de trabajo
on:                                                                       # Configuración de activadores
  push:                                                                   # Activar en eventos de push
    branches: [main]                                                      # Ramas objetivo para el push
  pull_request:                                                           # Activar en eventos de pull request
    branches: [main]                                                      # Ramas objetivo para el pull request
jobs:                                                                     # Definición de los trabajos
  test:                                                                   # Trabajo de pruebas
    name: Test API en Node.js ${{ matrix.node }}                          # Nombre del trabajo con la versión de Node.js
    runs-on: ubuntu-latest                                                # Sistema operativo en el que se ejecutará
    strategy:                                                             # Estrategia de matriz
      matrix:                                                             # Definición de matriz
        node: [16.x, 18.x, 22.x]                                                # Versiones de Node.js a probar
    steps:                                                                # Pasos del trabajo
      - name: Checkout del código                                         # Nombre del paso
        uses: actions/checkout@v3                                         # Acción para clonar el repositorio
      - name: Configurar Node.js                                          # Nombre del paso
        uses: actions/setup-node@v3                                       # Acción para configurar Node.js
        with:                                                             # Parámetros de configuración
          node-version: ${{ matrix.node }}                                # Versión de Node.js según la matriz
      - name: Cachear dependencias npm                                    # Nombre del paso
        uses: actions/cache@v3                                            # Acción para cachear dependencias
        with:                                                             # Parámetros de configuración
          path: ~/.npm                                                    # Ruta del caché
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Clave del caché basada en el sistema operativo y el archivo de bloqueo
          restore-keys: |                                                 # Claves de restauración
            ${{ runner.os }}-node-                                        # Prefijo de restauración
      - name: Instalar dependencias                                       # Nombre del paso
        run: npm ci                                                       # Comando para instalar dependencias
      - name: Ejecutar pruebas con Jest                                   # Nombre del paso
        run: npm test                                                     # Comando para ejecutar pruebas
      - name: Reportar éxito                                              # Nombre del paso
        if: success()                                                     # Condición para éxito
        run: echo "API funcional en Node ${{ matrix.node }}"              # Mensaje de éxito
      - name: Reportar error                                              # Nombre del paso
        if: failure()                                                     # Condición para error
        run: echo "Falla detectada en los tests para Node ${{ matrix.node }}" # Mensaje de error